What is numpy?
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

Numpy Arrays Vs Python Sequences


*   NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original
*   The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.
*   NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.
*  A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

Its a mathemathical library numby had a data type called numpy array . Created an array of same data type ie. its homogenous.



Creating Numpy array

In [ ]:
# np.array
import numpy as np

# creating the np array- it just needs one list
# 1D - can be called as vector
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
# 2D and 3D - can be callled as matrix
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# datatype
# create float datatype array
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
# create complex datatype array
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
# np.arange - way to create a numpy array - works same as range in python
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# with reshape - converting it to another shape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# np.ones and np.zeroes - provide tuple
# np.ones can be used to initialize the array and in neural networks for same
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random
np.random.random((3,4))

array([[0.76182084, 0.10664466, 0.83839055, 0.249824  ],
       [0.61116587, 0.43665292, 0.22309063, 0.38525767],
       [0.14758897, 0.25304843, 0.74648267, 0.57151773]])

In [ ]:
# np.linspace - linear space - we provide range with how many numbers we want to
# Generates points at equal distance between 2 points or range
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
# ndim = number of dimensions
a1.ndim
a2.ndim
a3.ndim

3

In [ ]:
# shape - dimension
a1.shape
a2.shape

(3, 4)

In [ ]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# size - number of items
a3.size

8

In [ ]:
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
# itemsize - how much space it occupy in memory
a2.itemsize

8

In [ ]:
a4 = np.arange(10,dtype=np.int32)
a4.itemsize

4

In [ ]:
# dtype - what is datatype of the item
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


Changing Datatype

In [ ]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [ ]:
# scalar Operations - we use single numpy array and perform operations using scalar

# arithmetic
a1 * 2
a1 + 2
a1 ** 2
a1 / 2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [ ]:
# relational
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
# vector operations - using 2 numpy arrays
# arithmetic
a1 + a2
a1 * a2
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

Array Functions

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[58., 22., 27.],
       [51., 50., 71.],
       [30., 49., 97.]])

In [ ]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.max(a1)

97.0

In [ ]:
np.max(a1,axis=1)

array([58., 71., 97.])

In [ ]:
np.min(a1)

22.0

In [ ]:
np.sum(a1)

455.0

In [ ]:
np.prod(a1)

889410058614000.0

In [ ]:
np.prod(a1, axis=0)

array([ 88740.,  53900., 185949.])

In [ ]:
# mean/median/std/var
np.mean(a1, axis=1)

array([35.66666667, 57.33333333, 58.66666667])

In [ ]:
np.median(a1)

50.0

In [ ]:
np.std(a1, axis=0)

array([11.8977122 , 12.97005097, 28.89059824])

In [ ]:
np.var(a1)

491.80246913580254

In [ ]:
# triinometric functions
np.sin(a1)

array([[ 0.99287265, -0.00885131,  0.95637593],
       [ 0.67022918, -0.26237485,  0.95105465],
       [-0.98803162, -0.95375265,  0.37960774]])

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents
np.log(a1)

array([[4.06044301, 3.09104245, 3.29583687],
       [3.93182563, 3.91202301, 4.26267988],
       [3.40119738, 3.8918203 , 4.57471098]])

In [ ]:
np.exp(a1)

array([[1.54553894e+25, 3.58491285e+09, 5.32048241e+11],
       [1.40934908e+22, 5.18470553e+21, 6.83767123e+30],
       [1.06864746e+13, 1.90734657e+21, 1.33833472e+42]])

In [ ]:
# round/floor/ceil
np.round(np.random.random((2,3))*100)

array([[15.,  1., 33.],
       [48., 23., 74.]])

In [ ]:
np.floor(np.random.random((2,3))*100)

array([[ 9., 84., 34.],
       [21., 32., 80.]])

In [ ]:
np.ceil(np.random.random((2,3))*100)

array([[57., 15., 42.],
       [11., 49., 93.]])

Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1[-1] # last item
a1[0] # first iitem

0

In [ ]:
a2[1,2] # row and column, finding element

6

In [ ]:
a3[1,0,1] # array,row,column

5

In [ ]:
a1[2:5:2]

array([2, 4])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
a2[:2,1::2]

array([[1, 3],
       [5, 7]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0,1,:]

array([3, 4, 5])

In [ ]:
a3[1,:,1]

array([10, 13, 16])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

Iterating

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1
for i in a1:
   print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping

In [ ]:
# reshape
a1 = np.arange(12).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# transpose
np.transpose(a1)
a1.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# ravel - concerts it to 1d any array
a1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Stacking

In [ ]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [ ]:
# Horizontal stacking - shape should be same
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting

In [ ]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
np.hsplit(a4,5)

ValueError: array split does not result in an equal division

In [ ]:
# vertical splitting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [ ]:
np.vsplit(a5,2)

ValueError: array split does not result in an equal division