### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [ ]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([43, 55, 37, 98, 42, 81,  9, 88, 36, 48,  6, 71, 54, 83, 21])

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[67, 75, 65, 78],
       [76, 88, 99, 78],
       [29, 44, 62,  9],
       [15, 27, 18, 40],
       [78, 61, 62, 53],
       [90, 55, 38, 12]])

In [ ]:
np.sort(a)

array([ 6,  9, 21, 36, 37, 42, 43, 48, 54, 55, 71, 81, 83, 88, 98])

In [ ]:
np.sort(a)[::-1] # decending wise sorting

array([98, 88, 83, 81, 71, 55, 54, 48, 43, 42, 37, 36, 21,  9,  6])

In [ ]:
np.sort(b)

array([[65, 67, 75, 78],
       [76, 78, 88, 99],
       [ 9, 29, 44, 62],
       [15, 18, 27, 40],
       [53, 61, 62, 78],
       [12, 38, 55, 90]])

In [ ]:
np.sort(b,axis=0) # column wise sorting

array([[15, 27, 18,  9],
       [29, 44, 38, 12],
       [67, 55, 62, 40],
       [76, 61, 62, 53],
       [78, 75, 65, 78],
       [90, 88, 99, 78]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [ ]:
# code
np.append(a,200)

array([ 43,  55,  37,  98,  42,  81,   9,  88,  36,  48,   6,  71,  54,
        83,  21, 200])

In [ ]:
b

array([[67, 75, 65, 78],
       [76, 88, 99, 78],
       [29, 44, 62,  9],
       [15, 27, 18, 40],
       [78, 61, 62, 53],
       [90, 55, 38, 12]])

In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[67., 75., 65., 78.,  1.],
       [76., 88., 99., 78.,  1.],
       [29., 44., 62.,  9.,  1.],
       [15., 27., 18., 40.,  1.],
       [78., 61., 62., 53.,  1.],
       [90., 55., 38., 12.,  1.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [ ]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [ ]:
# code
a.shape

(15,)

In [ ]:
np.expand_dims(a,axis=0)

array([[43, 55, 37, 98, 42, 81,  9, 88, 36, 48,  6, 71, 54, 83, 21]])

In [ ]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [ ]:
np.expand_dims(a,axis=1)

array([[43],
       [55],
       [37],
       [98],
       [42],
       [81],
       [ 9],
       [88],
       [36],
       [48],
       [ 6],
       [71],
       [54],
       [83],
       [21]])

In [ ]:
np.expand_dims(a,axis=1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
a

array([43, 55, 37, 98, 42, 81,  9, 88, 36, 48,  6, 71, 54, 83, 21])

In [ ]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  3,  5,  7, 11, 12, 13]),)

In [ ]:
# replace all values > 50 with 0 , condition-true-false
np.where(a>50,0,a)

array([43,  0, 37,  0, 42,  0,  9,  0, 36, 48,  6,  0,  0,  0, 21])

In [ ]:
np.where(a%2 == 0,0,a)

array([43, 55, 37,  0,  0, 81,  9,  0,  0,  0,  0, 71,  0, 83, 21])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [ ]:
# code
a

array([43, 55, 37, 98, 42, 81,  9, 88, 36, 48,  6, 71, 54, 83, 21])

In [ ]:
np.argmax(a)

3

In [ ]:
b

array([[67, 75, 65, 78],
       [76, 88, 99, 78],
       [29, 44, 62,  9],
       [15, 27, 18, 40],
       [78, 61, 62, 53],
       [90, 55, 38, 12]])

In [ ]:
np.argmax(b,axis=0) # column

array([5, 1, 1, 0])

In [ ]:
np.argmax(b,axis=1) # row

array([3, 2, 2, 3, 0, 0])

In [ ]:
# np.argmin
np.argmin(a)

10

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [ ]:
a

array([43, 55, 37, 98, 42, 81,  9, 88, 36, 48,  6, 71, 54, 83, 21])

In [ ]:
np.cumsum(a)

array([ 43,  98, 135, 233, 275, 356, 365, 453, 489, 537, 543, 614, 668,
       751, 772])

In [ ]:
b

array([[67, 75, 65, 78],
       [76, 88, 99, 78],
       [29, 44, 62,  9],
       [15, 27, 18, 40],
       [78, 61, 62, 53],
       [90, 55, 38, 12]])

In [ ]:
np.cumsum(b,axis=1)

array([[ 67, 142, 207, 285],
       [ 76, 164, 263, 341],
       [ 29,  73, 135, 144],
       [ 15,  42,  60, 100],
       [ 78, 139, 201, 254],
       [ 90, 145, 183, 195]])

In [ ]:
np.cumsum(b)

array([  67,  142,  207,  285,  361,  449,  548,  626,  655,  699,  761,
        770,  785,  812,  830,  870,  948, 1009, 1071, 1124, 1214, 1269,
       1307, 1319])

In [ ]:
# np.cumprod
np.cumprod(a)

array([                  43,                 2365,                87505,
                    8575490,            360170580,          29173816980,
               262564352820,       23105663048160,      831803869733760,
          39926585747220480,   239559514483322880, -1438018545393627136,
       -3866025156417658880, -7285438729603309568, -5420260731993088000])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [ ]:
a

array([43, 55, 37, 98, 42, 81,  9, 88, 36, 48,  6, 71, 54, 83, 21])

In [ ]:
np.percentile(a,100)

98.0

In [ ]:
np.percentile(a,50)

48.0

In [ ]:
np.median(a)

48.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
# code
a

array([43, 55, 37, 98, 42, 81,  9, 88, 36, 48,  6, 71, 54, 83, 21])

In [ ]:
np.histogram(a,bins=[0,50,100]) # showa number of item in particular bin

(array([8, 7]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience) # showa the relation

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [ ]:
a

array([43, 55, 37, 98, 42, 81,  9, 88, 36, 48,  6, 71, 54, 83, 21])

In [ ]:
items = [10,20,30,48,23]

a[np.isin(a,items)] # to  search multiple items

array([48])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [ ]:
a

array([43, 55, 37, 98, 42, 81,  9, 88, 36, 48,  6, 71, 54, 83, 21])

In [ ]:
np.flip(a)

array([21, 83, 54, 71,  6, 48, 36, 88,  9, 81, 42, 98, 37, 55, 43])

In [ ]:
b

array([[67, 75, 65, 78],
       [76, 88, 99, 78],
       [29, 44, 62,  9],
       [15, 27, 18, 40],
       [78, 61, 62, 53],
       [90, 55, 38, 12]])

In [ ]:
np.flip(b,axis=1)

array([[78, 65, 75, 67],
       [78, 99, 88, 76],
       [ 9, 62, 44, 29],
       [40, 18, 27, 15],
       [53, 62, 61, 78],
       [12, 38, 55, 90]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [ ]:
a

array([43, 55, 37, 98, 42, 81,  9, 88, 36, 48,  6, 71, 54, 83, 21])

In [ ]:
np.put(a,[0,1],[110,530])

In [ ]:
a

array([110, 530,  37,  98,  42,  81,   9,  88,  36,  48,   6,  71,  54,
        83,  21])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [ ]:
a

array([110, 530,  37,  98,  42,  81,   9,  88,  36,  48,   6,  71,  54,
        83,  21])

In [ ]:
np.delete(a,0) # you need to mention index of that number

array([530,  37,  98,  42,  81,   9,  88,  36,  48,   6,  71,  54,  83,
        21])

In [ ]:
np.delete(a,[0,2,4])

array([530,  98,  81,   9,  88,  36,  48,   6,  71,  54,  83,  21])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

you will get results in numpy array not sets

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(n,m) # only items unique un n

array([6, 7])

In [ ]:
np.setxor1d(m,n)  # prints every element leaving common elements in both

array([1, 2, 6, 7])

In [ ]:
m[np.in1d(m,1)]  # checks if given element is there or not

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [ ]:
a

array([110, 530,  37,  98,  42,  81,   9,  88,  36,  48,   6,  71,  54,
        83,  21])

In [ ]:
np.clip(a,a_min=25,a_max=75) # keeps the values in particular range

array([75, 75, 37, 75, 42, 75, 25, 75, 36, 48, 25, 71, 54, 75, 25])